[package]
name = "folder-scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-dialog = "0.6.3"
thiserror = "1.0.31"
bytesize = "1.1.0"
fltk = "^1.2"
fltk-theme = "0.4"
speedy2d = "1.7.0"